/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package punchcafe.niotrial;

import java.io.IOException;
import java.io.RandomAccessFile;

import java.net.InetSocketAddress;
import java.net.SocketAddress;
import java.nio.ByteBuffer;
import java.nio.channels.SocketChannel;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
        final var channel = SocketChannel.open().bind(new InetSocketAddress("localhost", 4451));
        System.out.println(channel.isOpen());
        System.out.println(channel.read(ByteBuffer.allocate(10)));
        channel.close();
    }
}
