/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jackson.practice;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        final var objectMapper = new ObjectMapper();

        try {
            final var jsonString = objectMapper.writeValueAsString(JsonCandidate.newBuilder().setMovie("Lord of the Rings").setRating(5).build());
            final var jsonObject = objectMapper.readValue(jsonString, JsonCandidate.class);
            System.out.println(jsonString);
            System.out.println(jsonObject);
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }
    }
}
